Import('*')

SimObject('ExampleObject.py', sim_objects=['ExampleObject'])
SimObject('TimeExampleObject.py', sim_objects=['TimeExampleObject'])

Source('example_object.cc')
Source('time_example_object.cc')

DebugFlag('TimeExampleObject')
